# Generated by Django 4.2.4 on 2023-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('modalidade', models.PositiveSmallIntegerField(choices=[('1', 'Solo'), ('2', 'Dupla'), ('3', 'Grupo'), ('4', 'Outros')], verbose_name='Modalidade')),
                ('email_1', models.EmailField(max_length=150, verbose_name='E-mail 01')),
                ('email_2', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail 02')),
                ('fone_1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato 01')),
                ('fone_1_tipo', models.PositiveSmallIntegerField(choices=[(1, 'Telefone'), (2, 'WhatsApp')], default=1, verbose_name='Contato 01 Tipo')),
                ('fone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato 02')),
                ('fone_2_tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], default=1, null=True, verbose_name='Contato 02 Tipo')),
                ('fone_3', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato 03')),
                ('fone_3_tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], default=1, null=True, verbose_name='Contato 03 Tipo')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=250, verbose_name='Endereço')),
                ('numero', models.IntegerField(default=0, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=250, null=True, verbose_name='Complemento')),
            ],
        ),
    ]
