# Generated by Django 4.2.4 on 2023-08-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incricao',
            name='fone_1',
            field=models.CharField(default=1, max_length=15, verbose_name='Contato 01'),
            preserve_default=False,
        ),
    ]
