# Generated by Django 4.2.4 on 2023-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_alter_incricao_fone_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='incricao',
            name='nome_artistico',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome Artistico'),
            preserve_default=False,
        ),
    ]
