# Generated by Django 4.2.4 on 2023-08-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0003_incricao_nome_artistico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incricao',
            name='nome_artistico',
            field=models.CharField(max_length=255, verbose_name='Nome Artístico'),
        ),
    ]
