# Generated by Django 4.2.4 on 2023-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0004_alter_incricao_nome_artistico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incricao',
            name='modalidade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Solo'), (2, 'Dupla'), (3, 'Grupo'), (4, 'Outros')], verbose_name='Modalidade'),
        ),
    ]
